### ISSUE TITLE
Step fails with null parameter value

### ISSUE THREAD

**Issue by aiannucci** [allure-framework/allure-java#150]
#### I'm submitting a ... 
  - [X] bug report

#### What is the current behavior?

Step annotation fails to process if you call the annotated method with a null parameter value.
Consider the following snippet:

```
  @Test
  public void someTest() throws Exception {
   CustomType customType = null;
   customAssert(customType);
  }

  @Step("Perform custom assertion")
  private void customAssert(CustomType parameter) throws Exception {
  // do something
  }
```
Relevant stacktrace lines when running the test:

```
java.lang.IllegalArgumentException
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
```

#### Please tell us about your environment:

| Allure version | 2.3.4 |
| --- | --- |
| Test framework | junit@4.12 |
| Allure integration | allure-testng@2.0-BETA17 |

**Comment by aiannucci** [comment]
Nevermind, seems like a problem in my implementation.
