### ISSUE TITLE
Add support for Java 9

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [allure-framework/allure-java#208]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Unable to start test cases under JDK9.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
`"C:\Program Files\Java\jdk-9.0.4\bin\java" -ea -javaagent:C:\Users\AlexanderPoleschuk\.m2\repository/org/aspectj/aspectjweaver/1.8.13/aspectjweaver-1.8.13.jar -Didea.test.cyclic.buffer.size=1048576 "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 181.2784.17\lib\idea_rt.jar=4327:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 181.2784.17\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 181.2784.17\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 181.2784.17\plugins\testng\lib\testng-plugin.jar;D:\Projects\LandsEnd\Automation\Autotest\automated-test-selenium\target\classes;C:\Users\AlexanderPoleschuk\.m2\repository\io\qameta\allure\allure-selenide\2.0-BETA22\allure-selenide-2.0-BETA22.jar;C:\Users\AlexanderPoleschuk\.m2\repository\io\qameta\allure\allure-java-commons\2.0-BETA22\allure-java-commons-2.0-BETA22.jar;C:\Users\AlexanderPoleschuk\.m2\repository\io\qameta\allure\allure2-model-api\1.0-BETA6\allure2-model-api-1.0-BETA6.jar;C:\Users\AlexanderPoleschuk\.m2\repository\io\qameta\allure\allure2-model-pojo\1.0-BETA6\allure2-model-pojo-1.0-BETA6.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\apache\tika\tika-core\1.14\tika-core-1.14.jar;C:\Users\AlexanderPoleschuk\.m2\repository\io\qameta\allure\allure2-model-jackson\1.0-BETA6\allure2-model-jackson-1.0-BETA6.jar;C:\Users\AlexanderPoleschuk\.m2\repository\com\fasterxml\jackson\module\jackson-module-jaxb-annotations\2.7.0\jackson-module-jaxb-annotations-2.7.0.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\aspectj\aspectjrt\1.8.10\aspectjrt-1.8.10.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\jooq\joor\0.9.6\joor-0.9.6.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\aspectj\aspectjweaver\1.8.13\aspectjweaver-1.8.13.jar;C:\Users\AlexanderPoleschuk\.m2\repository\io\qameta\allure\allure-testng\2.0-BETA22\allure-testng-2.0-BETA22.jar;C:\Users\AlexanderPoleschuk\.m2\repository\io\qameta\allure\allure-descriptions-javadoc\2.0-BETA22\allure-descriptions-javadoc-2.0-BETA22.jar;C:\Users\AlexanderPoleschuk\.m2\repository\commons-io\commons-io\2.5\commons-io-2.5.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\testng\testng\6.10\testng-6.10.jar;C:\Users\AlexanderPoleschuk\.m2\repository\com\beust\jcommander\1.48\jcommander-1.48.jar;C:\Users\AlexanderPoleschuk\.m2\repository\com\codeborne\selenide\4.10.01\selenide-4.10.01.jar;C:\Users\AlexanderPoleschuk\.m2\repository\io\github\bonigarcia\webdrivermanager\2.1.0\webdrivermanager-2.1.0.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\apache\httpcomponents\httpclient\4.5.3\httpclient-4.5.3.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\rauschig\jarchivelib\0.7.1\jarchivelib-0.7.1.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\apache\commons\commons-compress\1.9\commons-compress-1.9.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\apache\httpcomponents\httpcore\4.4.8\httpcore-4.4.8.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\seleniumhq\selenium\selenium-java\3.8.1\selenium-java-3.8.1.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\seleniumhq\selenium\selenium-api\3.8.1\selenium-api-3.8.1.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\seleniumhq\selenium\selenium-chrome-driver\3.8.1\selenium-chrome-driver-3.8.1.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\seleniumhq\selenium\selenium-edge-driver\3.8.1\selenium-edge-driver-3.8.1.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\seleniumhq\selenium\selenium-firefox-driver\3.8.1\selenium-firefox-driver-3.8.1.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\seleniumhq\selenium\selenium-ie-driver\3.8.1\selenium-ie-driver-3.8.1.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\seleniumhq\selenium\selenium-opera-driver\3.8.1\selenium-opera-driver-3.8.1.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\seleniumhq\selenium\selenium-remote-driver\3.8.1\selenium-remote-driver-3.8.1.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\seleniumhq\selenium\selenium-support\3.8.1\selenium-support-3.8.1.jar;C:\Users\AlexanderPoleschuk\.m2\repository\net\bytebuddy\byte-buddy\1.7.5\byte-buddy-1.7.5.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar;C:\Users\AlexanderPoleschuk\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\AlexanderPoleschuk\.m2\repository\com\google\code\gson\gson\2.8.2\gson-2.8.2.jar;C:\Users\AlexanderPoleschuk\.m2\repository\com\google\guava\guava\23.6-jre\guava-23.6-jre.jar;C:\Users\AlexanderPoleschuk\.m2\repository\com\google\code\findbugs\jsr305\1.3.9\jsr305-1.3.9.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\checkerframework\checker-compat-qual\2.0.0\checker-compat-qual-2.0.0.jar;C:\Users\AlexanderPoleschuk\.m2\repository\com\google\errorprone\error_prone_annotations\2.1.3\error_prone_annotations-2.1.3.jar;C:\Users\AlexanderPoleschuk\.m2\repository\com\google\j2objc\j2objc-annotations\1.1\j2objc-annotations-1.1.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\codehaus\mojo\animal-sniffer-annotations\1.14\animal-sniffer-annotations-1.14.jar;C:\Users\AlexanderPoleschuk\.m2\repository\net\lightbody\bmp\browsermob-core\2.1.5\browsermob-core-2.1.5.jar;C:\Users\AlexanderPoleschuk\.m2\repository\net\lightbody\bmp\littleproxy\1.1.0-beta-bmp-17\littleproxy-1.1.0-beta-bmp-17.jar;C:\Users\AlexanderPoleschuk\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.8.9\jackson-core-2.8.9.jar;C:\Users\AlexanderPoleschuk\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.8.9\jackson-databind-2.8.9.jar;C:\Users\AlexanderPoleschuk\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.8.9\jackson-annotations-2.8.9.jar;C:\Users\AlexanderPoleschuk\.m2\repository\dnsjava\dnsjava\2.1.8\dnsjava-2.1.8.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\slf4j\jcl-over-slf4j\1.7.25\jcl-over-slf4j-1.7.25.jar;C:\Users\AlexanderPoleschuk\.m2\repository\com\jcraft\jzlib\1.1.3\jzlib-1.1.3.jar;C:\Users\AlexanderPoleschuk\.m2\repository\io\netty\netty-all\4.0.51.Final\netty-all-4.0.51.Final.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\bouncycastle\bcprov-jdk15on\1.58\bcprov-jdk15on-1.58.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\bouncycastle\bcpkix-jdk15on\1.58\bcpkix-jdk15on-1.58.jar;C:\Users\AlexanderPoleschuk\.m2\repository\net\lightbody\bmp\mitm\2.1.5\mitm-2.1.5.jar;C:\Users\AlexanderPoleschuk\.m2\repository\com\codeborne\phantomjsdriver\1.4.4\phantomjsdriver-1.4.4.jar;C:\Users\AlexanderPoleschuk\.m2\repository\commons-codec\commons-codec\1.11\commons-codec-1.11.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\slf4j\slf4j-nop\1.7.25\slf4j-nop-1.7.25.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\jsoup\jsoup\1.11.2\jsoup-1.11.2.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\yaml\snakeyaml\1.19\snakeyaml-1.19.jar;C:\Users\AlexanderPoleschuk\.m2\repository\org\json\json\20180130\json-20180130.jar;C:\Users\AlexanderPoleschuk\.m2\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 181.2784.17\plugins\testng\lib\jcommander.jar" org.testng.RemoteTestNGStarter -usedefaultlisteners false -socket4326 @w@C:\Users\AlexanderPoleschuk\AppData\Local\Temp\idea_working_dirs_testng1.tmp -temp C:\Users\AlexanderPoleschuk\AppData\Local\Temp\idea_testng1.tmp
java.util.ServiceConfigurationError: org.testng.ITestNGListener: Provider io.qameta.allure.testng.AllureTestNg could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader.access$100(ServiceLoader.java:390)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:799)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1389)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:1017)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:966)
	at org.testng.TestNG.run(TestNG.java:1089)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlElement
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.<init>(JaxbAnnotationIntrospector.java:139)
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.<init>(JaxbAnnotationIntrospector.java:126)
	at io.qameta.allure.model.Allure2ModelJackson.createMapper(Allure2ModelJackson.java:26)
	at io.qameta.allure.FileSystemResultsWriter.<init>(FileSystemResultsWriter.java:30)
	at io.qameta.allure.AllureLifecycle.getDefaultWriter(AllureLifecycle.java:281)
	at io.qameta.allure.AllureLifecycle.<init>(AllureLifecycle.java:47)
	at io.qameta.allure.Allure.getLifecycle(Allure.java:30)
	at io.qameta.allure.testng.AllureTestNg.<init>(AllureTestNg.java:119)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:777)
	... 7 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlElement
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 20 more`

#### Please tell us about your environment:

| Allure version | 2.6.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure integration | allure-testng@2.0-BETA22 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by vbauer** [comment]
+1 We have the same problem

**Comment by issilin** [comment]
+1

**Comment by Juvat** [comment]
The report itself works fine for me with Java 10 but I can't get the `@Steps` etc. annotations to work.
