### ISSUE TITLE
AllureCucumber3Jvm breaks when using --dry-run

### ISSUE THREAD

**Issue by timtebeek** [allure-framework/allure-java#255]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
AllureCucumber3Jvm breaks when using --dry-run.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Create a project using cucumber-jvm 4.2.0 + JUnit + add `@CucumberOptions(dryRun=true, plugins = "....AllureCucumber3Jvm")`. Run it.

#### What is the expected behavior?
AllureCucumber3Jvm skips report generation, or generates an empty report; AllureCucumber3Jvm does not generate a stacktrace causing the entire execution of other plugins to fail.

#### What is the motivation / use case for changing the behavior?
It breaks runs for other plugins that require/function with `--dry-run` active.

#### Please tell us about your environment:
| Allure version | 2.7.0 |
| --- | --- |
| Test framework | cucumber-jvm@4.2.0 |
| Allure integration | allure-cucumber3-jvm@2.7.0 |
| Generate report using | JUnit |

#### Other information 
```
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at io.qameta.allure.cucumber3jvm.AllureCucumber3Jvm.handleHookStep(AllureCucumber3Jvm.java:267)
	at io.qameta.allure.cucumber3jvm.AllureCucumber3Jvm.handleTestStepFinished(AllureCucumber3Jvm.java:184)
	at cucumber.runner.AbstractEventPublisher.send(AbstractEventPublisher.java:45)
	at cucumber.runner.AbstractEventPublisher.sendAll(AbstractEventPublisher.java:52)
	at cucumber.runner.CanonicalOrderEventPublisher.handle(CanonicalOrderEventPublisher.java:18)
	at cucumber.runtime.formatter.Plugins$1.receive(Plugins.java:55)
	at cucumber.runner.AbstractEventPublisher.send(AbstractEventPublisher.java:38)
	at cucumber.runner.AbstractEventBus.send(AbstractEventBus.java:9)
	at cucumber.runner.TimeServiceEventBus.send(TimeServiceEventBus.java:3)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:134)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```

**Comment by baev** [comment]
Could you please edit the issue according to issue template https://github.com/allure-framework/allure-java/blob/master/.github/ISSUE_TEMPLATE.md ?

**Comment by timtebeek** [comment]
Sure sorry, was in a rush getting off the train; Updated the above. Might be of note that we use `cucumber-jvm:4.2.0`, but that's working fine otherwise.

**Comment by timtebeek** [comment]
Given the stacktrace, there's an `if` conditional just above at: https://github.com/allure-framework/allure-java/blob/master/allure-cucumber3-jvm/src/main/java/io/qameta/allure/cucumber3jvm/AllureCucumber3Jvm.java#L265
Perhaps it should also allow `SKIPPED` ?

**Comment by timtebeek** [comment]
Either that or it should know/handle that `event.result.getError()` can return `null` for a `--dry-run`, and not create an optional and directly call `.get()`.

**Comment by timtebeek** [comment]
I can make an MR if you guys just tell me what approach you're like.. This is blocking our upgrade to Cucumber 4.

**Comment by timtebeek** [comment]
Sorry I'm away on holiday for now, so haven't been able to check yet. Did you try this with cucumber 4.2? And any plans for a suitably named class?

**Comment by timtebeek** [comment]
I can see that's being tackled in: https://github.com/allure-framework/allure-java/pull/251/files
