### ISSUE TITLE
error when publishing the result

### ISSUE THREAD

**Issue by 11aleksandrmd11** [allure-framework/allure-java#341]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ 1] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Good day! Please tell me what caused the error:
cucumber.runtime.CucumberException: java.lang.IllegalAccessError: tried to access class cucumber.runtime.formatter.TestSourcesModel from class cucumber.runtime.formatter.TestSourcesModelProxy

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
I use
<dependency>
       <groupId>io.qameta.allure</groupId>
       <artifactId>allure-cucumber4-jvm</artifactId>
      <version>2.10.0</version>
   </dependency>
<dependency>
       <groupId>io.cucumber</groupId>
       <artifactId>cucumber-java</artifactId>
       <version>4.2.6<version>
       <type>jar</type>
     </dependency>
     <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-junit</artifactId>
        <version>4.2.3</version>
        <type>jar</type>
   </dependency>

in case of use Plugins
<plugins>io.qameta.allure.cucumber4jvm.AllureCucumber4Jvm</plugins>
the following error occurs

#### Please tell us about your environment:

| Allure version | 2.10.0 |
| junit version |  4.12 |
| maven | 3.5.3 |
| cucumber-java | 4.2.6 |

#### Other information 
cucumber.runtime.CucumberException: java.lang.IllegalAccessError: tried to access class cucumber.runtime.formatter.TestSourcesModel from class cucumber.runtime.formatter.TestSourcesModelProxy
        at cucumber.runtime.formatter.PluginFactory.newInstance(PluginFactory.java:107)
        at cucumber.runtime.formatter.PluginFactory.instantiate(PluginFactory.java:91)
        at cucumber.runtime.formatter.PluginFactory.create(PluginFactory.java:73)
        at cucumber.runtime.formatter.Plugins.createPlugins(Plugins.java:65)
        at cucumber.runtime.formatter.Plugins.<init>(Plugins.java:37)
        at cucumber.runtime.Runtime$Builder.build(Runtime.java:188)
        at cucumber.runtime.io.CucumberRunner.getRuntime(CucumberRunner.java:27)

        at cucumber.runtime.io.CucumberRunner.run(CucumberRunner.java:21)
        at cucumber.runtime.io.CucumberRunner.startTests(CucumberRunner.java:17)

        at ru.sbt.qa.ufs.start.RunTest.run(RunTest.java:54)
        at java.lang.Thread.run(Thread.java:745)
                        Caused by: java.lang.IllegalAccessError: tried to access class cucumber.runtime.formatter.TestSourcesModel from class cucumber.runtime.formatter.TestSourcesModelProxy
        at cucumber.runtime.formatter.TestSourcesModelProxy.<init>(TestSourcesModelProxy.java:30)
        at io.qameta.allure.cucumber4jvm.AllureCucumber4Jvm.<init>(AllureCucumber4Jvm.java:81)
        at io.qameta.allure.cucumber4jvm.AllureCucumber4Jvm.<init>(AllureCucumber4Jvm.java:97)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at cucumber.runtime.formatter.PluginFactory.newInstance(PluginFactory.java:101)
        ... 10 more

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by 11aleksandrmd11** [comment]
Find the problem. Not all the allure libraries were connected
