### ISSUE TITLE
allure-junit5@2.13.6 throws exception with maven-surefire-plugin

### ISSUE THREAD

**Issue by simple-elf** [allure-framework/allure-java#476]
#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?
Maven surefire plugin can't run tests using 2.13.6 version of allure-junit5 integration. 
On Gradle works without a problem, also downgrade the version to 2.13.5 solves the issue.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
An example project is here https://github.com/allure-examples/allure-junit5-maven

#### What is the expected behavior?
Maven surefire plugin runs tests without any problem, like on 2.13.5 version

#### Please tell us about your environment:
| Allure version | 2.13.6 |
| --- | --- |
| Test framework | junit5@5.6.2 |
| Allure integration | allure-junit5@2.13.6 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)
Here is an exception:
```# Created at 2020-10-01T10:27:41.226
org.apache.maven.surefire.util.SurefireReflectionException: java.lang.NoClassDefFoundError: org/junit/platform/commons/util/ClassNamePatternFilterUtils
	at org.apache.maven.surefire.util.ReflectionUtils.instantiateOneArg(ReflectionUtils.java:139)
	at org.apache.maven.surefire.booter.ForkedBooter.createProviderInCurrentClassloader(ForkedBooter.java:403)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.NoClassDefFoundError: org/junit/platform/commons/util/ClassNamePatternFilterUtils
	at org.junit.platform.launcher.core.LauncherFactory.loadAndFilterTestExecutionListeners(LauncherFactory.java:122)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:108)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:75)
	at org.junit.platform.surefire.provider.JUnitPlatformProvider.<init>(JUnitPlatformProvider.java:85)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.maven.surefire.util.ReflectionUtils.instantiateOneArg(ReflectionUtils.java:135)
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.junit.platform.commons.util.ClassNamePatternFilterUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

**Comment by asolntsev** [comment]
@simple-elf It is rather issue in the demo project, not in Allure. I have fixed it in PR https://github.com/allure-examples/allure-junit5-maven/pull/1

This issue can be closed.
