### ISSUE TITLE
Allure reports a TC as pass even if it has pending steps(last step) in a Scenario

### ISSUE THREAD

**Issue by sara-suku** [allure-framework/allure-java#601]
Environment of execution:

allure-cucumber5-jvm: 2.14.0
cucumber-java: 5.7.0

Issue: Cucumber Scenario has a undefined step{last step}. During execution, StepResult is passed as null as the below exception occured.
java.lang.IllegalStateException: Undefined Step. Please add step definition
	at io.qameta.allure.cucumber5jvm.AllureCucumber5Jvm.handlePickleStep(AllureCucumber5Jvm.java:390)
	at io.qameta.allure.cucumber5jvm.AllureCucumber5Jvm.handleTestStepFinished(AllureCucumber5Jvm.java:239)
	at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:45)
	at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:9)
	at io.cucumber.core.runtime.ThreadLocalRunnerSupplier$SynchronizedEventBus.send(ThreadLocalRunnerSupplier.java:100)
	at io.cucumber.core.runtime.ThreadLocalRunnerSupplier$LocalEventBus.send(ThreadLocalRunnerSupplier.java:68)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:58)

**Comment by sara-suku** [comment]
Please let me know if there are any updates?
