### ISSUE TITLE
Unable to map the json response to an object, getting "com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException"

### ISSUE THREAD

**Issue by Fanil-Suratwala** [allure-framework/allure-java#620]
**Describe the bug**

While deserializing our JSON response into an object, we get this exception : 
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException

We started getting this exception after integrating the allure report with our framework, if we remove allure we dont get this error.

**To Reproduce**
1] Deserialise the JSON response into POJO using Gson
2] Integrate the allure reports by adding the following maven dependencies
	

		<dependency>
			<groupId>io.qameta.allure</groupId>
			<artifactId>allure-testng</artifactId>
			<version>2.14.0</version>
		</dependency>
		
		<dependency>
			<groupId>io.qameta.allure</groupId>
			<artifactId>allure-java-commons</artifactId>
			<version>2.14.0</version>
		</dependency>

**Complete Exception :** 

```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "templates/www/admin/issues.html" (class API.Pojos.Response.Templates), not marked as ignorable (one known property: "templatesWwwAdminIssuesHtml"])
 at [Source: (StringReader); line: 1, column: 50] (through reference chain: API.Pojos.Response.FetchViewResponseBody["templates"]->API.Pojos.Response.Templates["templates/www/admin/issues.html"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3042)
	at com.fasterxml.jackson.databind.ObjectMapper$readValue$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.groovy:46)
	at io.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at io.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:58)
	at io.restassured.mapper.ObjectMapper$deserialize.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at io.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:238)
	at io.restassured.internal.mapping.ObjectMapping$parseWithJackson2$0.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240)
	at io.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:59)
	at io.restassured.internal.mapping.ObjectMapping$deserialize.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:231)
	at io.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:169)
	at API.APIHelper.APICalls.getNewIssuesViewId(APICalls.java:83)
```

Verified the field "templates/www/admin/issues.html" with the response and its correct.

**Screenshots :** 

i) API Response snippet : 
![image](https://user-images.githubusercontent.com/63437550/125435869-b7f61646-d4c8-415a-995d-5debe523da33.png)

ii) POJO class :
![image](https://user-images.githubusercontent.com/63437550/125436035-30cabdd4-0416-47d0-a34d-bcfb2a4ece32.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version  90.0.4430.212 

**Additional context**
We are using Gson to deserialize the response

**Comment by baev** [comment]
Not an Allure issue. Allure commons depends on latest Jackson, that may cause the issues for you. 

BTW we already shaded Jackson deps (not released yet)
