### ISSUE TITLE
Support for jdk 17

### ISSUE THREAD

**Issue by MeikeMertschFortum** [allure-framework/allure-java#801]
Our team is working with java jdk 17 and Allure sadly does not (yet) support that.
It has to be compiled in a lower version of jdk and 17 cannot do a strict verification of bytecode.

For now I am force-compile the tests in java 11, but that should only be an interim solution.

Let's prepare for the future 🚀

**Comment by baev** [comment]
We have no issues using Allure with Java 17 like at all. Could you please clarify what do you mean by saying Allure does not support it yet?

**Comment by MeikeMertschFortum** [comment]
That was a fast response!

Yes, here is a stack trace that I get wherever I use the @Steps Annotation:

```
Caused by: org.junit.platform.commons.JUnitException: ClassSelector [className = 'com.fortum.calvin.frontend.pageobjects.PreAuthPage'] resolution failed
	at app//org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
	at app//org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:102)
	at app//org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)
	at app//org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
	at app//org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:46)
	at app//org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
	at app//org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
	... 29 more
Caused by: java.lang.VerifyError: Expecting a stackmap frame at branch target 69
Exception Details:
  Location:
    com/fortum/calvin/frontend/pageobjects/PreAuthPage.goHome()Lcom/fortum/calvin/frontend/pageobjects/PreAuthPage; @10: invokestatic
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: b200 722a 2ab8 0078 3a04 b800 7e19 04b6
    0000010: 0082 2a4c 2bc0 0002 4d03 3eb2 0027 2cb4
    0000020: 0017 1229 b600 2db9 0032 0100 2cb4 0017
    0000030: 2cba 0046 0000 b900 4c02 0000 2bc0 0002
    0000040: 3a06 a700 103a 05b8 007e 1905 b600 8619
    0000050: 05bf b800 7eb6 0089 1906 b0            
  Exception Handler Table:
    bci [10, 69] => handler: 69

	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3427)
	at java.base/java.lang.Class.getMethods(Class.java:2019)
	at org.junit.platform.commons.util.ReflectionUtils.getDefaultMethods(ReflectionUtils.java:1518)
	at org.junit.platform.commons.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:1491)
	at org.junit.platform.commons.util.ReflectionUtils.findMethod(ReflectionUtils.java:1341)
	at org.junit.platform.commons.util.ReflectionUtils.isMethodPresent(ReflectionUtils.java:1242)
	at org.junit.jupiter.engine.discovery.predicates.IsTestClassWithTests.hasTestOrTestFactoryOrTestTemplateMethods(IsTestClassWithTests.java:50)
	at org.junit.jupiter.engine.discovery.predicates.IsTestClassWithTests.test(IsTestClassWithTests.java:46)
	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:67)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:134)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:185)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:125)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:91)
	... 34 more
```

our build.gradle.kts has this for Allure:

```
val allureVersion = "2.18.1"

allure {
    report {
        version.set(allureVersion)
    }
    adapter {
        autoconfigure.set(true)
        frameworks {
            junit5 {
                adapterVersion.set(allureVersion)
            }
        }
    }
}
```

the gradle plugin version is `2.10.0`

**Comment by MeikeMertschFortum** [comment]
And one more comment: I am super happy to hear that you have no trouble. That means it could turn out that I made a stupid beginner's mistake and there is an easy fix for it. And that would be something to celebrate 🥳

**Comment by MeikeMertschFortum** [comment]
I just got another piece of information: My colleague pointed to this error description: https://java.tutorialink.com/nosuchmethoderror-when-using-step-annotation-in-allure2/ which is not using gradle and has the same symptoms. (although I cannot say which java version they use)

**Comment by MeikeMertschFortum** [comment]
Ha! we figured it out. 
It was the aspectJ version

`aspectjVersion.set("1.9.9.1")`

did the trick. Unfortunately the docs on https://docs.qameta.io/allure/#_gradle_5 are a little outdated and it wasn't very obvious what to look for, how to add that aspectJ version and what the newest version could be. But now we are flying
thanks. Sometimes all it needs is someone who says "But I have it working!". Thanks
